package com.pp.week6.assign3;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;

import com.pp.week6.assign3.Register;
import com.pp.week6.assign3.dao.RegisterDoa;
import com.pp.week6.assign3.hash.Md5HashingClass;


/**

@Pratik Patel
@Tuesday, February 17, 2026
 
Description -  Data from RegFormPage.jsp is received by the Servlet and assigned to the Register object using setter methods.
 			   This parameterization, combined with the use of PreparedStatements, adds a critical layer of security to prevent SQL 
 			   injection.Before proceeding, the registerSelect() method is called to verify if the user_id already exists in 
 			   the database; if a match is found, the registration process is terminated to prevent duplicates.
 			   Additionally, the system performs a ReType check to ensure password matching before any other processing occurs; 
 			   once validated, the password is then secured using MD5 hashing prior to database insertion.


*/




/**
 * Servlet implementation class RegisterServlet
 */
@WebServlet("/RegisterServlet")
public class RegisterServlet extends HttpServlet {
	
	
	private RegisterDoa rtDao;
	
	
	public void init() {
		rtDao = new RegisterDoa();
		
	}
	
	
	
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public RegisterServlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.getWriter().append("Served at: ").append(request.getContextPath());
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		
		// RegFormPage.jsp values are sent here
		String user_id = request.getParameter("user_id");
		String password = request.getParameter("password");
		String retype_password = request.getParameter("retype_password");
		String mobile = request.getParameter("mobile");
		String captcha = request.getParameter("captcha");
		String email = request.getParameter("email");
		
		
		//password matching is checked
		if(!password.equals(retype_password)) {
			response.sendRedirect("RegFormPage.jsp?PASSWORDS_DO_NOT_MATCH");
		    return;
		}
		
		if(!captcha.equals("KJBRKP")) {
			response.sendRedirect("RegFormPage.jsp?INCORRECT_CAPTCHA");
		    return;
			
		}
		
		
		// we encrypt the password
		Md5HashingClass md5 = new Md5HashingClass();
		String hashedPassword = md5.getMd5(password);
		
		
		// just for troubleshooting
		//System.out.println("Your HashCode Generated by MD5 is: " + hashedPassword);
		
		
		
		//we set the values
		Register rt = new Register();
		rt.setUser_id(user_id);
		rt.setPassword(hashedPassword);
		rt.setEmail(email);
		rt.setMobile(mobile);
	
		// we check if the user_id value is already inside the db before inserting
		try {
			
			if(rtDao.registerSelect(rt)) {
				response.sendRedirect("RegFormPage.jsp?FOUND_USER_TRY_AGAIN");
				return;
				
			}else {
				rtDao.registerInsert(rt);
				
			}
			
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		  
		  
		  
		 
		
		response.sendRedirect("CompleteRegPage.jsp");
		
		
		
		
		
		
		
		
		
		
		
	}

}















